require "user.impatient"
require "user.options"
require "user.keymaps"
require "user.plugins"
require "user.colorscheme"
require "user.bufferline"
require "user.gitsigns"
require "user.treesitter"
require "user.autopairs"
require "user.indentline"
require "user.lualine"
require "user.nvimtree"
require "user.toggleterm"
require "user.project"
require "user.telescope"
-- require "user.nord"
